#!/bin/bash

# RCSIM Industrial Hardening - UDEV Setup Script
# Ten skrypt konfiguruje stałe dowiązania symboliczne (symlinks) dla LiDARu i Kamery USB.
# Należy go uruchomić na HOŚCIE Raspberry Pi (poza Dockerem).

set -e

RULE_FILE="/etc/udev/rules.d/99-rcsim.rules"
echo "--- RCSIM UDEV Setup ---"

# 1. Wykrywanie LiDARu LD08 (CP210x USB to UART)
# Standardowo: ID 10c4:ea60
LIDAR_VENDOR="10c4"
LIDAR_PRODUCT="ea60"

# 2. Wykrywanie Kamery USB (V4L2)
# Tu może być różnie, spróbujemy znaleźć pierwszą kamerę USB
USB_CAM_PATH=$(v4l2-ctl --list-devices 2>/dev/null | grep -A 1 "USB" | grep "/dev/video" | head -n 1 | xargs)

echo "Tworzenie reguł w $RULE_FILE..."

# Nagłówek pliku
sudo bash -c "cat << EOF > $RULE_FILE
# RCSIM Persistent Symlinks
# Generated by setup_udev.sh

# LiDAR LD08 (CP2102)
SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"$LIDAR_VENDOR\", ATTRS{idProduct}==\"$LIDAR_PRODUCT\", SYMLINK+=\"rcsim/lidar\"

EOF"

# Dodanie reguły dla kamery USB jeśli znaleziona
if [ -n "$USB_CAM_PATH" ]; then
    CAM_DEV=$(basename $USB_CAM_PATH)
    # Pobieranie atrybutów dla konkretnego urządzenia
    CAM_VENDOR=$(udevadm info -a -p $(udevadm info -q path -n /dev/$CAM_DEV) | grep "idVendor" | head -n 1 | cut -d'"' -f2)
    CAM_PRODUCT=$(udevadm info -a -p $(udevadm info -q path -n /dev/$CAM_DEV) | grep "idProduct" | head -n 1 | cut -d'"' -f2)
    
    if [ -n "$CAM_VENDOR" ] && [ -n "$CAM_PRODUCT" ]; then
        echo "Wykryto Kamerę USB: $CAM_VENDOR:$CAM_PRODUCT"
        sudo bash -c "cat << EOF >> $RULE_FILE
# USB Camera
SUBSYSTEM==\"video4linux\", ATTRS{idVendor}==\"$CAM_VENDOR\", ATTRS{idProduct}==\"$CAM_PRODUCT\", ATTR{index}==\"0\", SYMLINK+=\"rcsim/camera\"
EOF"
    fi
else
    echo "⚠️ Nie wykryto kamery USB. Pomiń tę regułę (prawdopodobnie używasz CSI)."
fi

echo "Przeładowanie reguł udev..."
sudo udevadm control --reload-rules
sudo udevadm trigger

echo "--- GOTOWE ---"
echo "Sprawdź: ls -la /dev/rcsim/"
